[workspace]
members = [
    "node",
    "pallets/template",
	"pallets/demoquad",
	"pallets/identity-primitives",
	"pallets/simple-identity",
	"pallets/identity-primitives",
    "runtime",
]
[profile.release]
panic = "unwind"
